### ISSUE TITLE
Inav documentation and Wiki

### ISSUE THREAD

**Issue by pilotnbr1** [bortek/EZ-WifiBroadcast#181]
Need some INav specific examples for setting up EZ. I am an INav user and might get to this and have been intending on doing it but time is always my issue...

Additionally I think any graphics should be consistent with what has already been added to the wiki for pixhawk.

**Comment by careyer** [comment]
@pilotnbr1 : I am sorry but I do not have any iNAV flight controller so I cannot really help in this regard. However if you need specific graphics feel free to reach out to me. I will then try to put something together in Photoshop then.

**Comment by pilotnbr1** [comment]
@careyer I am sitting down to work on the rc INav portion of the wiki (thanks for getting a start on that) and I think the whole rc portion could benefit from some reorganization. I want to get your blessing first as most of it was your work.

My proposal for the rc section pages is-

- General
- Ardupilot specific
- Inav specific
- Builds

To my there needs to be one general page that makes clear the two routes for rc. Serial or Mavlink. There seems to be confusion with users, mixing telemetry and rc. Obviously many users just use telemetry and usually rc users seem to use rc and telemetry simultaneously. I think here some of the General Notes and warnings @rodizio1 mentioned on rcgroups today can also be described

I think the ardupilot should be condensed and combined into one page.

The INav page I’ll just expand on and work on right now.

Reliable setups or builds should be just builds. While the examples presented are indeed reliable I think they are more demonstrations of what is possible at the extreme end of the spectrum. I look at that page and say “wow” that’s nice! 

Thoughts?

**Comment by pilotnbr1** [comment]
I just updated the rc INAV Page. Thoughts? What did I screw up, leave out, etc? 
Please, Jump in and change it if you don’t like it!

I couldn’t remember about setting baud rate in the INav configurator... it should be mentioned.

Also @rodizio1 is there a better serial protocol? I happened to choose sumd and it works but others use ibus.. and reports of msp. Should we recommend one of the others?

**Comment by careyer** [comment]
> 
> @careyer I am sitting down to work on the rc INav portion of the wiki (thanks for getting a start on that) and I think the whole rc portion could benefit from some reorganization. I want to get your blessing first as most of it was your work.

You are welcome! 

> My proposal for the rc section pages is-
> 
>     * General
Generated an empty page for that... please go ahead and make a short writeup that explains the two routes (MAVlink & regular RC protocols)

>     * Ardupilot specific
Consolidated both Ardupilot specific pages and named them "RC with Ardupilot"

>     * Inav specific
OK, I named it "RC with iNAV"

>     * Builds
Alright. I named this "DIY builds"


 
> To my there needs to be one general page that makes clear the two routes for rc. Serial or Mavlink. There seems to be confusion with users, mixing telemetry and rc. Obviously many users just use telemetry and usually rc users seem to use rc and telemetry simultaneously. I think here some of the General Notes and warnings @rodizio1 mentioned on rcgroups today can also be described

Sure! Go ahead add this to the "General" page at will.

> I think the ardupilot should be condensed and combined into one page.

Did that already - see above
 
> The INav page I’ll just expand on and work on right now.

Thank you very much. Take care to get everthing right :smirk: 

> Reliable setups or builds should be just builds. While the examples presented are indeed reliable I think they are more demonstrations of what is possible at the extreme end of the spectrum. I look at that page and say “wow” that’s nice!

Renamed that "DIY builds" (see above). Thank you very much for the flowers. I'd really like to see some more builds here. Preferably also some that are not so much at the extreme end of what is possible. We should however take care not to show off builds with too much of a cable clutter because that might scare off people who might easily get the impression that it is irresponsible to fly with a mess quickly thrown together and fixated with hotglue all over the place :grin:

**Comment by careyer** [comment]
> 
> 
> I just updated the rc INAV Page. Thoughts? What did I screw up, leave out, etc?
> Please, Jump in and change it if you don’t like it!
> 
> I couldn’t remember about setting baud rate in the INav configurator... it should be mentioned.
> 
> Also @rodizio1 is there a better serial protocol? I happened to choose sumd and it works but others use ibus.. and reports of msp. Should we recommend one of the others?

Thank you very much! You did a decent job. I just changed the "Supported SOCs" link for "Supported WiFi Adapters" since you are refering to that only Atheros AR9271 is supported ;-) 
Also changed the spelling of "iNav" consistenly all over the document.

**Comment by rodizio1** [comment]
Regarding the protocols: sumd, ibus and xbus as well as msp are all fine from a technical standpoint, doesn't really matter which one. I implemented sumd,ibus and xbus to give flexibility and because they are 'standardized', and probably won't change eventually, like msp did several times (leading to msp currently only working with totally outdated cleanflight versions). msp has one advantage though: Baudrate is not fixed at 115200 and thus you can run it at 19200 with softserial (115200 doesnt work with softserial) in case you don't have enough hardware uarts.

**Comment by pilotnbr1** [comment]
Thanks for the help and input guys. Good stuff regarding protocols. One thing I just stumbled across is the potential for ibus to share serial rx and telemetry on one port. So maybe it would have an advantage if wbc could parse ibus telemetry, if I’m understanding that correctly.

 I hope you find the new layout logical. In the RC General page I tried not to be mavlink or INav specific. Just stuff that holds true for both setups.

For the INav page I did add a note regarding telemetry and serial rx being forced to separate uarts because it seems to be a common use. I am now not so sure that is a correct statement. It seems there may be some situations such as msp being allowed to share rc control and telemetry on the same uart. @rodizio1 please take a look and edit/delete as you see fit. I read the INav issue between you and digitaly discussing your proposed enhancement to INav. Frustrating to read...

Probably can close this issue soon unless more conversation develops..

**Comment by careyer** [comment]
Very well done! The RC section looks neat and nice now! =)
Good job on consolidating much of the information on the 'General' page. :+1: 

@rodizio1 : Regarding the regular RC protocols, are all of them supported to their full extent (e.g. but not limited to: max number of channels as of their specification) or are there any limitations or differences between them? If there is it might be worth mentioning this somewhere. I could not find information on this but maybe I haven't looked hard enough. It would be nice if you could tell us here in short. Thank you very much.
