### ISSUE TITLE
HELP please, pi Zero work only with 1.5  ?! 

### ISSUE THREAD

**Issue by DomenicoPatella** [bortek/EZ-WifiBroadcast#206]
I downloaded the last version 1.6 RC6 and mountend on PI Zero as Air Pi , but the first message show 
ERROR wifobroadcast config filw not found .. and the the last message is
mount : \ boot is busy
I tried also 1.6RC5 and the problem it's the same.
With 1.5 everything work  
Someone can understand the problem ?
Thk

![errorlog](https://user-images.githubusercontent.com/6493675/53991864-c66de200-412b-11e9-8b43-add1ea277356.png)

**Comment by DomenicoPatella** [comment]
..Solved 
SOLVED  copied 16 file  to understand if the problem was coming from GPIO and it's true.
I  don't know wich configuration is used ..anwyway

![immagine](https://user-images.githubusercontent.com/6493675/53993146-d5a25f00-412e-11e9-9f05-570e53ac258b.png)

**Comment by rodizio1** [comment]
It checks the GPIO pins during bootup, if it uses a different configfile number, it is because the Raspberry reports those GPIO pins as "connected to ground".

Either you have one or more GPIO pins really connected to ground, or something is broken with the GPIO pins.

The error message is indeed not very clear (and contains a typo ...). I'll check if it's possible to add the number to the error message so that it's easier to see what is going on.

**Comment by DomenicoPatella** [comment]
Ok , but there is an information in log file to understand wich number of configuration is used  now? 
Anyway i will check the status of the GPIO pins , thank for the support

**Comment by rodizio1** [comment]
No, unfortunately there is no information which file gets used as the main script in /root/.profile is not aware of the configfile copying, this is done in wbcconfig.sh.
