### ISSUE TITLE
1.6RC2 how to set manual video bitrate ?

### ISSUE THREAD

**Issue by roque-canales** [bortek/EZ-WifiBroadcast#62]

**Comment by rodizio1** [comment]
I assume you set something and the bitrate is way too low? If yes, then the issue is, that manual bitrate needs to be specified in bits/s, not kbit/s. Just add three zeros.

Having said that, I recommend leaving it on auto, as this will tell you if something is wrong, i.e. when the channel is already in use, you will see that you get a lower bitrate.

**Comment by roque-canales** [comment]
Thank you for this reply

**Comment by rodizio1** [comment]
Manual bitrate setting is now in kbit/s since version 1.6RC3.
