### ISSUE TITLE
Impossible to calibrate ardupilot sensor through mission planner over UDP

### ISSUE THREAD

**Issue by roque-canales** [bortek/EZ-WifiBroadcast#82]

**Comment by rodizio1** [comment]
I think this is probably caused by an issue with outdated mavlink libraries that has recently been identified. 

If you have some basic linux knowledge, you can try if replacing the librarirs with a newer version, see here:https://www.rcgroups.com/forums/showpost.php?p=39028277&postcount=3741

If not, this will also be included in 1.6rc4 (which I hope to have ready soon)

**Comment by roque-canales** [comment]
thank you for this feedback Rodizio!

**Comment by rodizio1** [comment]
1.6RC4 is released, hopefully it should work now.

**Comment by rodizio1** [comment]
@roque-canales Did you have a chance to test?

**Comment by roque-canales** [comment]
Hello, Yes I test it, there is many improvement, now we can see many other data, so it's perfect !

About calibration I can calibrate the accelerometers but no the compass..... But I think that there is a mission planner mistake.

I will retest it.

**Comment by rodizio1** [comment]
Thanks for reporting back.

**Comment by roque-canales** [comment]
it works (copter 3.5.5 and WBC 1.6!!

you can close the issue

**Comment by careyer** [comment]
This issue will be solved with the upcomming release with MAVlink v2
